import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { MAX_PLAYERS } from '@blackjack/game-logic';
import { ErrorToast } from '../components/ErrorToast';
import styles from './LobbyScreen.module.css';
export function LobbyScreen({ roomCode, gameState, isHost, isConnected, error, send, }) {
    const players = gameState?.players ?? [];
    const canStart = isHost && players.length >= 1;
    const gameInProgress = gameState !== null && gameState.phase !== 'waiting_for_players';
    return (_jsxs("div", { className: styles.container, children: [_jsx(ErrorToast, { message: error }), _jsxs("div", { className: styles.card, children: [_jsxs("div", { className: styles.header, children: [_jsx("h2", { className: styles.title, children: gameInProgress ? 'Game in progress' : 'Waiting for players' }), _jsxs("div", { className: styles.connectionStatus, children: [_jsx("span", { className: isConnected ? styles.dotOnline : styles.dotOffline }), isConnected ? 'Connected' : 'Connecting...'] })] }), _jsxs("div", { className: styles.roomCodeBox, children: [_jsx("p", { className: styles.roomCodeLabel, children: "Room code" }), _jsx("p", { className: styles.roomCode, children: roomCode })] }), gameInProgress ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: styles.playerList, children: [_jsxs("p", { className: styles.playerCount, children: [players.length, " / ", MAX_PLAYERS, " players in this round"] }), players.map((player, i) => (_jsxs("div", { className: styles.playerRow, children: [_jsx("span", { className: styles.playerIndex, children: i + 1 }), _jsx("span", { className: styles.playerName, children: player.name }), i === 0 && _jsx("span", { className: styles.hostBadge, children: "Host" })] }, player.id)))] }), _jsxs("p", { className: styles.waitingMsg, children: ["Round ", gameState.roundNumber, " is underway.", _jsx("br", {}), "You'll automatically join at the start of the next round."] })] })) : (_jsxs(_Fragment, { children: [_jsxs("div", { className: styles.playerList, children: [_jsxs("p", { className: styles.playerCount, children: [players.length, " / ", MAX_PLAYERS, " players"] }), players.map((player, i) => (_jsxs("div", { className: styles.playerRow, children: [_jsx("span", { className: styles.playerIndex, children: i + 1 }), _jsx("span", { className: styles.playerName, children: player.name }), i === 0 && _jsx("span", { className: styles.hostBadge, children: "Host" })] }, player.id))), Array.from({ length: MAX_PLAYERS - players.length }).map((_, i) => (_jsxs("div", { className: `${styles.playerRow} ${styles.emptySlot}`, children: [_jsx("span", { className: styles.playerIndex, children: players.length + i + 1 }), _jsx("span", { className: styles.playerName, children: "Waiting..." })] }, `empty-${i}`)))] }), isHost ? (_jsx("button", { className: styles.startBtn, onClick: () => send({ type: 'START_GAME' }), disabled: !canStart, children: canStart ? '▶ Start Game' : 'Need at least 1 player' })) : (_jsx("p", { className: styles.waitingMsg, children: "Waiting for the host to start the game..." }))] }))] })] }));
}
